### ISSUE TITLE
No connection to Asterisk

### ISSUE THREAD

**Issue by Brianchat** [danleeb/GreenJ#2] opened 2012-05-14 15:18 UTC
Just installed Asterisk 1.8 on Debian 6.0. Using a windows XP laptop and Windows 7desktop both x-lite and zoiper connect. GreenJ just gives the spinning dial and why I take to be 'Connecting to Server' in Deutsche.

I have downloaded the VS2008 distributable and have tried using the 'basic phone' sample from the library page but still no luck.

The log only records 'System starting', error file is createdbut is empty.

Connection settings are:
var settings = {
    host:   '10.0.0.111',
    name:   '1001',
    secret: '1001'
};

Am I missing something?

**Comment by danleeb** [comment] 2012-05-16 09:18
Hello brian,

you could set the log level to 0 in your settings.conf file (/home/[user]/.greenj/settings.conf: log_level=0). A .log file is then created in the application directory with additional information (something like "[ERROR] pjsip-account: [408]   Request Timeout").
- We had to set NAT to Yes for your asterisk extensions (Asterisk 1.8.4. with FreePBX as administration tool), otherwise connecting failed.
- Setting of an outbound proxy is currently not supported (will be included in version 1.1)
- GreenJs standard port for SIP connections is 5060

**Comment by Brianchat** [comment] 2012-05-26 16:14
Many thanks for the response. 
If I change the log_level it works perfectly, without any error messages to the log.If I change it back to 0 I just get the white screen again.

**Comment by danleeb** [comment] 2012-05-29 08:52
That's odd; I couldn't reproduce your problem with the log_level setting.

But I just committed an update that should fix problems when using the current Qt version (4.8) with a local phone website (which resulted in white screens).

Thanks for your feedback!

**Closed as completed** 2012-05-29 08:53 UTC
